### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by RaptaG**

### CODE REVIEW

**Comment by RaphiMC** [comment]
Thank you

**Comment by RaptaG** [comment]
Could you please fix #19 plz btw?

**Comment by RaphiMC** [comment]
I am currently fixing it, but it won't be released until I fixed #16

**Comment by RaptaG** [comment]
Thanks!

**Comment by RaphiMC** [comment]
Would you mind adding download batches for modrinth and curseforge into the readme like its in sodium's readme?

**Comment by RaptaG** [comment]
Nope, I would add them in the first place but I forgor 💀

**Pull request merged**
