### PR TITLE
1.18.2 Backport

### PR DESCRIPTION
**Pull request by StockiesLad**
More or less a straightforward backport.

### CODE REVIEW

**Comment by RaphiMC** [comment]
Thank you. I will take a closer look after I fix a pretty severe issue I introduced with the latest release. Would appreciate if you could update your fork with the changes, once I pushed them

**Comment by RaphiMC** [comment]
I have created a 1.18.2 branch. You can rebase your PR onto that branch in the meanwhile

**Comment by StockiesLad** [comment]
> Thank you. I will take a closer look after I fix a pretty severe issue I introduced with the latest release. Would appreciate if you could update your fork with the changes, once I pushed them

yeah no problem!

**Comment by StockiesLad** [comment]
For your own sanity, I highly recommend adding a disclaimer that 1.18.2 is community-driven so people don't say "BuT Why IS ThiS mOd Not UPdAtINg 1.18.2 AnYmOrE"

**Comment by StockiesLad** [comment]
Btw, im in ur discord so ping when ur ready. I will respond faster if u do that.

**Comment by RaphiMC** [comment]
Yeah thank you tho. Whats your discord tag/name?

**Comment by StockiesLad** [comment]
Viktor Reznov#2386

**Comment by StockiesLad** [comment]
upstreamed

**Comment by RaphiMC** [comment]
My fix still has a bug, so I am not finished yet, I will notify you when I am ready

**Comment by StockiesLad** [comment]
alright, sounds good

**Pull request merged**
